### ISSUE TITLE
Ensure that there is a RestClient.Builder in the application context

### ISSUE THREAD

**Issue by habuma** [spring-projects/spring-ai#563] opened 2024-04-08 12:49 UTC
When Spring AI auto-configures various client implementations, it depends upon a `RestClient.Builder` to create a `RestClient` for those client implementations. That works fine when the project uses the Spring MVC starter because a `RestClient.Builder` will be auto-configured. But when using the Spring WebFlux starter, no such `RestClient.Builder` is auto-configured and the application will fail to start.

AFAIK, this happens in all recent versions of Spring AI, including 0.8.1 and 1.0.0-SNAPSHOT.

To reproduce, create a simple Spring AI application with a dependency on the WebFlux starter and almost any model starter...such as the OpenAI starter. You do not need to write any code to reproduce this problem. Just create a new Spring Boot project with the aforementioned starters and then try to run it. The application will fail to start and you'll get the following error:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method openAiChatClient in org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration required a bean of type 'org.springframework.web.client.RestClient$Builder' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.web.client.RestClient$Builder' in your configuration.
```

If Spring AI were to ensure the existence of a `RestClient.Builder` then the application would start and function fine, even when using WebFlux.

**Comment by Johnnymic** [comment] 2024-04-15 11:35
can i help

**Comment by markpollack** [comment] 2024-04-17 02:44
@habuma implementation suggestions?

**Comment by ChrisToplikar** [comment] 2024-04-17 18:04
In case someone is looking for a temporary work around, adding org.springframework.boot:spring-boot-starter-web to the dependencies will resolve the issue.

**Comment by tzolov** [comment] 2024-04-30 12:55
It is not acceptable to add starters to utility/library. It is ok to add it to the end application, which is the current behaviour. 
The goal is to have some defaults (non starter) in the library.

**Comment by iromu** [comment] 2024-06-28 20:24
Should not spring-ai use HTTP Interface Client, and detect (and use) either WebClient or RestClient builders?

**Comment by yueyangbo123** [comment] 2024-06-29 02:13
If you have configured "web-application-type", you can try to remove it and restart
from
```
server:
  port: 8091
spring:
  application:
    name: Spring-ai-demo
  main:
    web-application-type: reactive
```
to
```
server:
  port: 8091
spring:
  application:
    name: Spring-ai-demo
```

**Comment by markpollack** [comment] 2024-07-22 20:05
Related to #524

**Comment by yuge1805** [comment] 2024-07-25 07:33
![image](https://github.com/user-attachments/assets/1217d53e-3be3-4008-a279-8863c98f61cb)
RestClient#Builder bean is only defined in web application, you need to define one yourself. I tried it in webflux and it worked fine

**Comment by csterwa** [comment] 2024-09-10 19:24
Duplicate of #524

**Closed by csterwa** 2024-09-10 19:24 UTC
Labels: enhancement, configuration, follow up
