### ISSUE TITLE
Some links in Javadoc are invalid

### ISSUE THREAD

**Issue by laglangyue** [spring-projects/spring-ai#392] opened 2024-03-04 02:43 UTC
Because fully qualified names were not used and only class names were used, some links in Javadoc became invalid

![image](https://github.com/spring-projects/spring-ai/assets/35491928/269ee1b8-a1f2-46a1-9b97-08b68dc732b4)

This will lead to errors in generating Javadoc pages in the future. Do we have tools to check and resolve this issue during compilation

**Comment by ThomasVitale** [comment] 2024-07-11 07:08
@laglangyue do you still experience this issue? I couldn't reproduce it from my IDE.

**Comment by markpollack** [comment] 2024-07-22 15:30
This renders ok, though I'm sure we have javadoc errors to prune.  Closing the issue

![image](https://github.com/user-attachments/assets/1dd2b794-60c4-45a2-825a-31c893c70adf)

**Closed by markpollack** 2024-07-22 15:30 UTC
Labels: help wanted
