### ISSUE TITLE
OpenAi Stream miss some data

### ISSUE THREAD

**Issue by wangyulong-patsnap** [spring-projects/spring-ai#876] opened 2024-06-17 10:04 UTC
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
When I use stream output with OpenAI, I found some times there are some data missed.

**Environment**
1.0.0-SNAPSHOT

**Steps to reproduce**
I debugged the code and found that the issue likely occurs in the following section of the code. I noticed that "ChatCompletion before handling" prints the data returned by OpenAI, but "ChatCompletion after handling" does not print anything, indicating that the data is lost at this step. However, I am not very familiar with Flux, so could you please assist in locating and fixing the issue?
![image](https://github.com/spring-projects/spring-ai/assets/20552372/c8b53c91-0bf5-481f-9704-c8b457fbceaf)

**Comment by wangyulong-patsnap** [comment] 2024-06-17 10:06
I never use function call, so isToolFunctionCall in method "handleFunctionCallOrReturnStream" is always false

**Comment by mkleine** [comment] 2024-06-26 10:09
We observed the same. Returning the result as a flux gives incomplete results. Is anybody working on this issue?

**Comment by mfadili** [comment] 2024-06-29 07:42
Indeed, observed the same issue.

**Comment by didalgolab** [comment] 2024-06-29 12:05
It works fine for me. I use Spring AI with OpenAI default API endpoints in streaming mode and I didn't noticed any issues. You need to provide reproducible example.

I have also run a quick JUnit test for completeness, which passes successfully::
```java
	@Test
	void streamCompletenessTest() throws InterruptedException {
		UserMessage userMessage = new UserMessage(
				"List ALL natural numbers in range [1, 1000]. Make sure to not omit any.");
		Prompt prompt = new Prompt(List.of(userMessage));
		Flux<ChatResponse> flux = streamingChatModel.stream(prompt);

		StringBuilder stitchedResponseContent = new StringBuilder();
		CountDownLatch latch = new CountDownLatch(1);

		flux.subscribe(
				resp -> stitchedResponseContent.append(resp.getResult().getOutput().getContent()),
				err -> {
					System.err.println("Error occurred: " + err.getMessage());
					latch.countDown();
				},
				() -> {
					System.out.println("Flux completed");
					latch.countDown();
				}
		);

		boolean completed = latch.await(120, TimeUnit.SECONDS);
		if (!completed) {
			throw new AssertionError("Flux did not complete within the timeout period");
		}

		System.out.println("LLM responded: " + stitchedResponseContent);
		IntStream.rangeClosed(1, 1000).forEach(n -> {
			assertThat(stitchedResponseContent).contains(String.valueOf(n));
		});
	}
```
```
Flux completed
LLM responded: Sure! Here is the complete list of natural numbers from 1 to 1000:

1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
...
991, 992, 993, 994, 995, 996, 997, 998, 999, 1000.

Tests passed: 1 of 1 test
```

**Comment by cy1665** [comment] 2024-07-01 02:54
Indeed, observed the same issue.

**Comment by mfadili** [comment] 2024-07-22 00:55
Could this issue be related to this one in openai ?
https://community.openai.com/t/4o-and-4-api-output-has-typo-missing-words/869225

**Comment by markpollack** [comment] 2024-07-22 23:10
Is the issue the use of `doOnNext` vs `subscribe`?

**Comment by wangyulong-patsnap** [comment] 2024-07-23 01:58
> Is the issue the use of `doOnNext` vs `subscribe`?问题是 `doOnNext` 使用 vs `subscribe` 吗？

I used OpenAiChatModel.stream

**Comment by cy1665** [comment] 2024-07-23 05:45
> Is the issue the use of `doOnNext` vs `subscribe`?


> Could this issue be related to this one in openai ? https://community.openai.com/t/4o-and-4-api-output-has-typo-missing-words/869225

I added the origin log, openai output is normal.

 I rewrite OpenAiChatModel to remove the swithmap() , it's work normal now.

**Comment by cy1665** [comment] 2024-07-23 05:49
I also replace the flatMap to concatMap, because it's may causes output order problems.

**Comment by uwilken** [comment] 2024-07-23 10:21
Same issue here. Looks like the streaming API is working differently for different chat client implementations.
With bedrock anthropic i get full responses. With open ai (gpt-4-0) I receive incomplete answers.

The code is as simple as that:
```
  @PostMapping(value = "/flux", produces = MediaType.TEXT_PLAIN_VALUE)
  public Flux<String> streamData() {

    return chatClient.prompt().user("who is joe biden?")
            .stream()
            .content();
  }

```

Example open ai response:
```
Joe Biden is an American politician and attorney who serves as the46 president of the United He was born20,194, in, Pennsylvania. Biden began his political career in when he was the U from Delaware, serving from1973 to2009. He gained national prominence as a of the Foreign Relations as a vice president Barack Obama.
...
```
> He was born20,194,

Example anthropic response:
```
 Here is a summary of key information about Joe Biden:

- Full Name: Joseph Robinette Biden Jr.
- Born: November 20, 1942 (age 80) in Scranton, Pennsylvania
- Political Party: Democratic
...
```

**Comment by sobychacko** [comment] 2024-07-23 23:01
Based on the information provided above, here is a simple integration test against OpenAI. It works as expected every time I run it. Could someone please take a look at this test and see if we can reproduce the problems mentioned on this issue? That way, we can triage it further. I am trying to make it fail so we can see the issue in the test itself. 
```
@Test
void streamCompletenessTest() throws InterruptedException {
    UserMessage userMessage = new UserMessage(
		    "List ALL natural numbers in range [1, 1000]. Make sure to not omit any.");
    Prompt prompt = new Prompt(List.of(userMessage));
    
    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);
    
    Flux<ChatResponse> chatResponseFlux = streamingChatModel.stream(prompt)
		    .doOnNext(chatResponse -> {
			    String responseContent = chatResponse.getResults().get(0).getOutput().getContent();
			    answer.append(responseContent);
		    }).doOnComplete(() -> {
			    System.out.println(answer);
			    latch.countDown();
		    });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    IntStream.rangeClosed(1, 1000).forEach(n -> {
	    assertThat(answer).contains(String.valueOf(n));
    });
}
```

**Comment by sobychacko** [comment] 2024-07-24 20:50
We added this test above as part of the test suite. See the commit: https://github.com/spring-projects/spring-ai/commit/4d41080d455b3584aa10ec5c7046144890de852c

It passes on our CI system. As I indicated above, if you encounter this issue, please review that test and see if you can reproduce it. Thanks!

**Comment by wangyulong-patsnap** [comment] 2024-07-25 01:48
> @wangyulong-patsnap Could you try this test and see if it doesn't work for you? Please advise on a way to make this test fail, so that we can try to reproduce your scenario. Thanks!

I tried this test, and it's working normally now. I'm unable to reproduce the issue at this moment, though it was consistently reproducible before. When it was consistently occurring, I attempted using the same model with the langchain4j framework for streaming output, and it worked fine.

**Comment by uwilken** [comment] 2024-07-25 09:58
I tried to reproduce the unit test, I modified it and found out that there seem to be a problem with `org.springframework.ai.chat.client.ChatClient.ChatClientRequest.StreamPromptResponseSpec#content`.

Here is my test code:
working:
```
  @Test
  void streamCompletenessTestWithChatClientWorking() throws InterruptedException {
    UserMessage userMessage = new UserMessage(
            "Who is joe biden?");
    Prompt prompt = new Prompt(List.of(userMessage));

    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);

    ChatClient chatClient = ChatClient.builder(openAiChatModel).build();

    Flux<ChatResponse> chatResponseFlux = chatClient.prompt(prompt).stream()
            .chatResponse()
            .doOnNext(chatResponse -> {
              String responseContent = chatResponse.getResults().get(0).getOutput().getContent();
              answer.append(responseContent);
            }).doOnComplete(() -> {
              latch.countDown();
            });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    System.out.println(answer);
    assertThat(answer).contains("the 46th ");
  }

```

Broken test:

```
@Test
  void streamCompletenessTestWithChatClientBidenBroken() throws InterruptedException {
    UserMessage userMessage = new UserMessage(
            "Who is joe biden?");
    Prompt prompt = new Prompt(List.of(userMessage));

    StringBuilder answer = new StringBuilder();
    CountDownLatch latch = new CountDownLatch(1);

    ChatClient chatClient = ChatClient.builder(openAiChatModel).build();

    //The #content() method seems to swallow the blanks
    Flux<String> chatResponseFlux = chatClient.prompt(prompt).stream().content()
            .doOnNext(chatResponse -> {
              answer.append(chatResponse);
            }).doOnComplete(() -> {
              latch.countDown();
            });
    chatResponseFlux.subscribe();
    assertThat(latch.await(120, TimeUnit.SECONDS)).isTrue();
    System.out.println(answer);
    assertThat(answer).contains("the 46th ");
  }

```
At least `chatClient.prompt(prompt).stream().content()` seems to swallow leading blanks.

**Comment by mkleine** [comment] 2024-07-25 10:06
> ```
>   @PostMapping(value = "/flux", produces = MediaType.TEXT_PLAIN_VALUE)
>   public Flux<String> streamData() {
> 
>     return chatClient.prompt().user("who is joe biden?")
>             .stream()
>             .content();
>   }
> ```

I've extended this example and it turns out that the `doOnNext` approach gives complete responses, while webflux returns incomplete responses if we're just passing the flux to the framework.

The following example writes complete answers to the log:
```
  @PostMapping(value = "/complete", produces = MediaType.TEXT_PLAIN_VALUE)
  public Flux<String> complete() {
      StringBuilder answer = new StringBuilder();

      Flux<ChatResponse> flux = chatClient.prompt()
              .user("Who is Joe Biden?").stream()
              .chatResponse()
              .doOnNext(chatResponse -> {
                String responseContent = ofNullable(chatResponse.getResults())
                        .filter(results -> !results.isEmpty())
                        .map(results -> results.get(0))
                        .map(Generation::getOutput)
                        .map(AssistantMessage::getContent)
                        .orElse("");
                answer.append(responseContent);
              }).doOnComplete(() -> {
                System.out.println(answer);
              });

    flux.subscribe();
    return Mono.just("complete result in log").flux();
  }
```

while this example returns incomplete responses to the client

```
  @PostMapping(value = "/incomplete", produces = MediaType.TEXT_PLAIN_VALUE)
  public Flux<String> incomplete() {
      return chatClient.prompt()
              .user("Who is Joe Biden?").stream()
              .chatResponse()
              .map(f -> ofNullable(f).map(ChatResponse::getResult)
                      .map(Generation::getOutput)
                      .map(AssistantMessage::getContent)
                      .orElse("")
              );
  }

**Comment by mkleine** [comment] 2024-07-25 10:08
> At least `chatClient.prompt(prompt).stream().content()` seems to swallow leading blanks.

This sounds very much like https://github.com/spring-projects/spring-ai/issues/1089, doesn't it?

**Comment by sobychacko** [comment] 2024-07-30 19:31
Fixed via this issue: https://github.com/spring-projects/spring-ai/issues/1089

**Closed by sobychacko** 2024-07-30 19:31 UTC
Labels: model client, openai
