### ISSUE TITLE
Support AWS Bedrock

### ISSUE THREAD

**Issue by jogueber** [spring-projects/spring-ai#66] opened 2023-10-30 12:49 UTC
Please do a quick search on Github issues first, the feature you are about to request might have already been requested.

**Expected Behavior**
It would be nice to add support for [AWS Bedrock](https://www.aboutamazon.com/news/aws/aws-amazon-bedrock-general-availability-generative-ai-innovations). 
 

**Current Behavior**
No support yet
**Context**
In general AWS Bedrock will probably be relevant since a lot of people are on AWS and will probably not migrate everything over. 

I could pitch in time to make it  happen. 
As a first pitch I would probably start with inference

**Comment by markpollack** [comment] 2023-12-04 20:35
Closing as is a duplicate of #67

**Closed** 2023-12-18 23:23 UTC
