### ISSUE TITLE
Chat History example

### ISSUE THREAD

**Issue by williamspindox** [spring-projects/spring-ai#396] opened 2024-03-04 13:28 UTC
Hi, can you please provide some examples to use chat history with chatcompletition?
Thanks

**Comment by hemeda3** [comment] 2024-03-04 23:54
Just a suggestion :D 


- I would do it this way using the prompt object itself!


```Java

	private void openAiChatRunUseInstruction() {
		List<Message> messages = new ArrayList<>();
		Prompt prompt = new Prompt(messages);

		sendPromptAndUpdate(prompt, "What is the population of Canada?");
		sendPromptAndUpdate(prompt, "What is the capital?");

		prompt.getInstructions().forEach(System.out::println);

	}

	private void sendPromptAndUpdate(Prompt prompt, String userPrompt) {
		prompt.getInstructions().add(new UserMessage(userPrompt));
		ChatResponse resp = openAiChatClient.call(prompt);
		prompt.getInstructions().add(resp.getResult().getOutput());
	}

```
Output:

> UserMessage{content='What is the population of Canada?', properties={}, messageType=USER}
> AssistantMessage{content='As of 2021, the population of Canada is approximately 38 million.', properties={role=ASSISTANT}, messageType=ASSISTANT}
> UserMessage{content='What is the capital?', properties={}, messageType=USER}
> AssistantMessage{content='The capital of Canada is Ottawa.', properties={role=ASSISTANT}, messageType=ASSISTANT}
> 

- Or maybe this way using new container to organize output ? 

```Java

	private void openAiChatRunWithList() {
		List<Message> messages = new ArrayList<>();

		String userPrompt1 = "What is the population of Canada?";
		addMessageAndCallApi(messages, userPrompt1);

		String userPrompt2 = "And what is the capital (only name)?";
		addMessageAndCallApi(messages, userPrompt2);

		messages.forEach(System.out::println);
		/**
		 * UserMessage{content='What is the population of Canada?', properties={}, messageType=USER}
		 * AssistantMessage{content='As of 2021, the estimated population of Canada is around 38 million.', properties={role=ASSISTANT}, messageType=ASSISTANT}
		 * UserMessage{content='And what is the capital (only name)?', properties={}, messageType=USER}
		 * AssistantMessage{content='The capital of Canada is Ottawa.', properties={role=ASSISTANT}, messageType=ASSISTANT}
		 */
	}

	private void addMessageAndCallApi(List<Message> messages, String userPrompt) {
		messages.add(new UserMessage(userPrompt));
		Prompt prompt = new Prompt(messages);
		ChatResponse resp = openAiChatClient.call(prompt);
		resp.getResults().forEach(r -> {
			messages.add(r.getOutput());
		});
	}
	
```
Output:

> UserMessage{content='What is the population of Canada?', properties={}, messageType=USER}
> AssistantMessage{content='As of 2021, the estimated population of Canada is around 38 million.', properties={role=ASSISTANT}, messageType=ASSISTANT}
> UserMessage{content='And what is the capital (only name)?', properties={}, messageType=USER}
> AssistantMessage{content='The capital of Canada is Ottawa.', properties={role=ASSISTANT}, messageType=ASSISTANT}
>

**Comment by tzolov** [comment] 2024-03-12 14:25
Hi @hemeda3 , we will start working on an official Spring AI ChatHistory abstraction very soon. 
Until then perhaps you can use something like this: https://github.com/tzolov/playground-flight-booking/blob/main/src/main/java/ai/spring/demo/ai/playground/services/ChatHistory.java

**Comment by shandilya07** [comment] 2024-03-31 19:15
I don't think there is any implicit support for chat for now, the idea is to send the previous discussion as part of the prompt itself and this helps the chat bot maintain the context of the application. I made a video in details on this topic where I built a chat bot using open ai chat completion API. Here is the video if you wish to watch https://www.youtube.com/watch?v=83KTwxCCe9I

Moreover, please note that LLMs are stateless by default and by design. So all the chatbots like chat gpt or Gemini they implement the context awareness in the message thread on the application level. So effectively, maintaining the chat context/awareness/history over a LLM is a matter of having a wrapper of some sort. Chat GPT web portal does so by sending something called as a conversation_id

<img width="806" alt="image" src="https://github.com/spring-projects/spring-ai/assets/135587831/567d175b-d8ad-44b0-87d3-8f3eb48f2662">

**Comment by shandilya07** [comment] 2024-03-31 19:19
> I don't think there is any implicit support for chat for now, the idea is to send the previous discussion as part of the prompt itself and this helps the chat bot maintain the context of the application. I made a video in details on this topic where I built a chat bot using open ai chat completion API. Here is the video if you wish to watch https://www.youtube.com/watch?v=83KTwxCCe9I
> 
> Moreover, please note that LLMs are stateless by default and by design. So all the chatbots like chat gpt or Gemini they implement the context awareness in the message thread on the application level. So effectively, maintaining the chat context/awareness/history over a LLM is a matter of having a wrapper of some sort. Chat GPT web portal does so by sending something called as a conversation_id
> 
> <img alt="image" width="806" src="https://private-user-images.githubusercontent.com/135587831/318295289-567d175b-d8ad-44b0-87d3-8f3eb48f2662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTI4NTEsIm5iZiI6MTcxMTkxMjU1MSwicGF0aCI6Ii8xMzU1ODc4MzEvMzE4Mjk1Mjg5LTU2N2QxNzViLWQ4YWQtNDRiMC04N2QzLThmM2ViNDhmMjY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxOTE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDYwNTQ0MDQyOWZiNTA5YWUxNWFiOTNmY2Q4MGUwMThkNWZkN2E4NGRjZTg4MzNiMzZhYzUzYmM1N2E5ZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JmSy-Ke6JQDOWw9e6SF6TO3isVjHI3s0G1LWAQYXDbY">

One downside of this approach is accumulation of large amount of tokens quickly which is both bad of being within  the context window limit and the billing. However, one common optimisation is to either summarise the discussion so far (by using the chat api itself) so the context text becomes compact and smaller yet meaningful enough to convey the context or maintain context for only last K messages in a given session (chat window which is tracked by web ui of chat gpt). I have discussed all these information in more details in the video linked above.

**Comment by sebastianblesgen** [comment] 2024-05-19 18:14
Isn't the purpose of feature like "thread" provided by OpenAI? I guess abstraction could use it as implementation (or in-memory list of history messages, should it be decided by configuration?).

**Comment by cikichen** [comment] 2024-05-31 08:07
> > I don't think there is any implicit support for chat for now, the idea is to send the previous discussion as part of the prompt itself and this helps the chat bot maintain the context of the application. I made a video in details on this topic where I built a chat bot using open ai chat completion API. Here is the video if you wish to watch https://www.youtube.com/watch?v=83KTwxCCe9I
> > Moreover, please note that LLMs are stateless by default and by design. So all the chatbots like chat gpt or Gemini they implement the context awareness in the message thread on the application level. So effectively, maintaining the chat context/awareness/history over a LLM is a matter of having a wrapper of some sort. Chat GPT web portal does so by sending something called as a conversation_id
> > <img alt="image" width="806" src="https://private-user-images.githubusercontent.com/135587831/318295289-567d175b-d8ad-44b0-87d3-8f3eb48f2662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTI4NTEsIm5iZiI6MTcxMTkxMjU1MSwicGF0aCI6Ii8xMzU1ODc4MzEvMzE4Mjk1Mjg5LTU2N2QxNzViLWQ4YWQtNDRiMC04N2QzLThmM2ViNDhmMjY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxOTE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDYwNTQ0MDQyOWZiNTA5YWUxNWFiOTNmY2Q4MGUwMThkNWZkN2E4NGRjZTg4MzNiMzZhYzUzYmM1N2E5ZDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JmSy-Ke6JQDOWw9e6SF6TO3isVjHI3s0G1LWAQYXDbY">
> 
> One downside of this approach is accumulation of large amount of tokens quickly which is both bad of being within the context window limit and the billing. However, one common optimisation is to either summarise the discussion so far (by using the chat api itself) so the context text becomes compact and smaller yet meaningful enough to convey the context or maintain context for only last K messages in a given session (chat window which is tracked by web ui of chat gpt). I have discussed all these information in more details in the video linked above.

need [Assistants API](https://platform.openai.com/docs/assistants)

**Comment by ThomasVitale** [comment] 2024-07-10 13:48
Spring AI 1.0.0-M1 introduced support for chat history via the new ChatClient API: https://docs.spring.io/spring-ai/reference/api/chatclient.html#_chat_memory You can find an example here: https://github.com/ThomasVitale/llm-apps-java-spring-ai/tree/main/00-use-cases/chatbot

@williamspindox Can this issue be closed?

**Comment by markpollack** [comment] 2024-07-22 15:32
Closing, please reopen if necessary @williamspindox

**Closed by markpollack** 2024-07-22 15:32 UTC
