### ISSUE TITLE
The model output names doesn't contain expected: last_hidden_state

### ISSUE THREAD

**Issue by caixiaomao** [spring-projects/spring-ai#204] opened 2023-12-29 08:14 UTC
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
According to the official documentation at https://docs.spring.io/spring-ai/reference/api/embeddings/onnx.html, the following error is reported:
```shell
Caused by: java.lang.IllegalArgumentException: The model output names doesn't contain expected: last_hidden_state
	at org.springframework.util.Assert.isTrue(Assert.java:111) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.ai.embedding.TransformersEmbeddingClient.afterPropertiesSet(TransformersEmbeddingClient.java:180) ~[spring-ai-transformers-0.8.0-20231226.133308-17.jar:0.8.0-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1820) ~[spring-beans-6.1.2.jar:6.1.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-6.1.2.jar:6.1.2]
	... 16 common frames omitted
```
Model conversion command：
```shell
optimum-cli export onnx --model E:\AI\models\all-MiniLM-L6-v2 --framework pt --monolith --task feature-extraction E:\AI\models\onnx-models\all-MiniLM-L6-v2
```

**Environment**
spring-ai.version: 0.8.0-SNAPSHOT
jdk: 21

```xml
<dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-transformers-spring-boot-starter</artifactId>
            <version>${spring-ai.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-pgvector-store</artifactId>
            <version>${spring-ai.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-transformers</artifactId>
            <version>${spring-ai.version}</version>
        </dependency>
```

**Steps to reproduce**
Steps to reproduce the issue.

**Expected behavior**

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by markpollack** [comment] 2024-01-07 16:37
Thanks so much for reporting this.  I've assigned it to the 0.8.0 release.

**Comment by tzolov** [comment] 2024-01-09 10:55
Hi @caixiaomao , 
Can you please elaborate on this issue? 

For example, If you need the `all-MiniLM-L6-v2` ONNX model, later is already generated and used by default by the `TransformersEmbeddingClient`.  
So you can use it as a Bean:

```java
@Bean
public EmbeddingClient transformersEmbeddingClient() {
   return new TransformersEmbeddingClient();
}
```

Or create it manually, in which case you have to explicitly call the `afterPropertiesSet()`.
```java
TransformersEmbeddingClient embeddingClient = new TransformersEmbeddingClient();
embeddingClient.afterPropertiesSet();
```
(have a look a the `TransformersEmbeddingClientTests`)

In both cases the `all-MiniLM-L6-v2` model is loaded. 

If you are building your own ONNX model , the documentation suggests and i've been successfully used the following command:
`optimum-cli export onnx --model sentence-transformers/all-MiniLM-L6-v2 onnx-output-folder`

Not sure what your parameters `--framework pt --monolith --task feature-extraction` are supposed to do?

**Comment by caixiaomao** [comment] 2024-01-11 01:16
If the above parameters are not used, the following error will be reported during model conversion：
![image](https://github.com/spring-projects/spring-ai/assets/5171685/74c1a9e7-9d55-47da-bb07-10e4f86362a9)
RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually.

**Comment by caixiaomao** [comment] 2024-01-11 01:22
I have reviewed the official documentation and found the following content：
```
This exports an ONNX graph of the checkpoint defined by the --model argument. As you can see, the task was automatically detected. This was possible because the model was on the Hub.

For local models, providing the --task argument is needed or it will default to the model architecture without any task specific head
```

**Comment by tzolov** [comment] 2024-01-11 13:00
@caixiaomao 
I'm not that familiar with huggingface optimum nor is spring-ai dependent on it. 
Perhaps you will find more help about how to use Optimum/ONNX on the [huggingface optimum](https://huggingface.co/docs/optimum/onnxruntime/overview) forum? 

For the purpose of the `TransformersEmbeddingClient` you should be able to use any transformer model exported into [ONNX Runtime](https://onnxruntime.ai/) format.  There many different ways an tools for ONNX exporting. The optimum-cli is one of them that makes it easy to generate the ONNX from the models available on Huggingface's Hub. 
Having said this should you use  hub model reference: `--model sentence-transformers/all-MiniLM-L6-v2` rather pointing to a local copy? 

Also if find the [Netron](https://github.com/lutzroeder/netron) useful to explore the ONNX graphs visually.

**Comment by caixiaomao** [comment] 2024-01-12 01:26
Thank you very much, I will give it a try.

**Comment by iikka-v** [comment] 2024-02-25 15:34
FWIW, I'm seeing the same error with the 0.8.1-SNAPSHOT
Minimal steps to reproduce:
1) download model (to resources)
```optimum-cli export onnx --model sentence-transformers/all-MiniLM-L6-v2 all-MiniLM-L6-v2```
2) Try to create client:
``` 
TransformersEmbeddingClient embeddingClient = new TransformersEmbeddingClient();
embeddingClient.setTokenizerResource("classpath:/all-MiniLM-L6-v2/tokenizer.json")
embeddingClient.setModelResource("classpath:/all-MiniLM-L6-v2/model.onnx");
embeddingClient.afterPropertiesSet();
``` 

==> fails with error 

```
Caused by: java.lang.IllegalArgumentException: The generative output names doesn't contain expected: last_hidden_state
	at org.springframework.util.Assert.isTrue(Assert.java:111)
	at org.springframework.ai.transformers.TransformersEmbeddingClient.afterPropertiesSet(TransformersEmbeddingClient.java:187)
```

The model is loaded correctly, and outputs are visible in the debugger, but the outputs do not match the expected (has "token_embeddings" and "sentence_embedding" instead of the expected "last_hidden_state")

using the default model works:
``` 
TransformersEmbeddingClient embeddingClient = new TransformersEmbeddingClient();
embeddingClient.afterPropertiesSet();
```
This seems to load model from https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/model.onnx, which does, indeed have the expected output. Quick look in Netron reveals quite a bit of other differences as well, which may indicate that the root cause is difference in the optimum or related environment. Here's what I used:
```
- `optimum` version: 1.17.1
- `transformers` version: 4.38.1
- Platform: macOS-14.3.1-arm64-arm-64bit
- Python version: 3.9.6
- Huggingface_hub version: 0.20.3
- PyTorch version (GPU?): 1.13.1 (cuda availabe: False)
- Tensorflow version (GPU?): 2.14.0 (cuda availabe: True)
```

**Comment by kush-298** [comment] 2024-04-09 17:08
Hi Everyone,
I encountered the same error while loading my model other than the default.

I exported the sentence-transformers/all-mpnet-base-v2 model into onnx format using the optimum cli as specified in the [documentation](https://docs.spring.io/spring-ai/reference/api/embeddings/onnx.html#_serialize_with_optimum_cli) 

`optimum-cli export onnx --model sentence-transformers/all-mpnet-base-v2 onnx-output-folder`

Create the embedding client

`@Bean("transformersEmbeddingClient")
    public EmbeddingClient embeddingClient() {
        return new TransformersEmbeddingClient();
    }`

Add the below properties in application.properties file

`spring.ai.embedding.transformer.tokenizer.uri=classpath:/embeddingModel/tokenizer.json
spring.ai.embedding.transformer.onnx.modelUri=classpath:/embeddingModel/model.onnx`

On startup getting the below error.

`Caused by: java.lang.IllegalArgumentException: The generative output names doesn't contain expected: last_hidden_state
	at org.springframework.util.Assert.isTrue(Assert.java:111) ~[spring-core-6.1.5.jar:6.1.5]
	at org.springframework.ai.transformers.TransformersEmbeddingClient.afterPropertiesSet(TransformersEmbeddingClient.java:202) ~[spring-ai-transformers-0.8.1.jar:0.8.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833) ~[spring-beans-6.1.5.jar:6.1.5]
	at org.springfra`

**Comment by diegopacheco** [comment] 2024-04-22 09:34
Same problem here. This last solution by @kush-298 works for me.
Here is my full code: https://github.com/diegopacheco/ai-playground/tree/main/pocs/spring-ai-ONNX-transformers-all-MiniLM-L6-v2/project

**Comment by masdeval** [comment] 2024-08-22 11:54
@kush-298  did you understand why sentence_embedding is not valid? I want to work with a model that only has sentence_embedding output. Would have any leads in how to make it work?

**Comment by viosay** [comment] 2024-08-30 01:31
I'm having the same issue

**Comment by markpollack** [comment] 2024-10-07 16:53
We have documented what to do in this case here - https://docs.spring.io/spring-ai/reference/api/embeddings/onnx.html#_errors_and_special_cases  

If there is any addition you would like to see added to the documentation, please reopen the issue.

**Closed by markpollack** 2024-10-07 16:53 UTC
Labels: to discuss, onxx, follow up
